# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
  end
 end
end
target 'homeWork_1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for homeWork_1
	
	pod 'IQKeyboardManagerSwift'
	pod 'Alamofire'
  pod 'RealmSwift', '~> 4.4.1'
	pod 'PinLayout'
	pod 'SwiftyJSON', '~> 4.0'
	pod 'SDWebImage', '~> 4.0'
	pod 'Firebase/Core'
  	pod 'Firebase/Database'
#  	pod 'Firebase/Auth'
#  	pod 'Firebase/Firestore'



end
